spring:
  application:
    name: CtsRest

ribbon:
  eureka:
    enabled: false

feign.hystrix.enabled: false

logging.level.edu.ucdavis.fiehnlab.cts.ctsRest: DEBUG

fiehnlab:
  cts:
    config:
      url: http://cts.fiehnlab.ucdavis.edu
      name: CtsWrapper
      connectTimeoutMillis: 1000
      readTimeoutMillis: 120000
